trigger:
  branches:
    include:
      - main 

pool:
  name: 'FraudEngineAgentPool' 

stages:

    - stage: 
      
      jobs:
        
        - job: BuildAndPublish
          
          steps:
            
            - task: VSBuild@1
              inputs:
                solution: '**/*.sln'
                platform: 'Any CPU'
                configuration: 'Release'
                msbuildArgs: '/t:Restore,Build'

            - task: CopyFiles@2
              inputs:
                Contents: '**/*.dacpac'
                TargetFolder: '$(Build.ArtifactStagingDirectory)'

            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'dacpac'


