
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

stages:

- stage: Build
  jobs:
  - job: Build
    steps:

    - task: VSBuild@1
      displayName: 'Restore and Build Solution'
      inputs:
        solution: '**/*.sln'
        platform: 'Any CPU'
        configuration: 'Release'
        msbuildArgs: '/t:Restore,Build'

    - task: CopyFiles@2
      displayName: 'Copy DACPAC'
      inputs:
        contents: '**/*.dacpac'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish DACPAC'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'dacpac'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployDatabase
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: dacpac

          - script: |
              dotnet tool install -g Microsoft.SqlPackage
              echo ##vso[task.prependpath]%USERPROFILE%\.dotnet\tools
            displayName: 'Install SqlPackage'

          - powershell: |
              Write-Host "Pipeline Workspace:"
              Get-ChildItem "$(Pipeline.Workspace)" -Recurse

              Write-Host "Listing DACPAC files..."

              $dacpacs = Get-ChildItem "$(Pipeline.Workspace)\dacpac" -Recurse -Filter *.dacpac

              if ($dacpacs.Count -eq 0) {
                  Write-Error "No DACPAC files found!"
                  exit 1
              }

              $dacpac = $dacpacs[0]

              Write-Host "Using DACPAC: $($dacpac.FullName)"

              sqlpackage /Action:Publish `
                /SourceFile:"$($dacpac.FullName)" `
                /TargetConnectionString:"Server=localhost;Database=FraudEngineDB;Trusted_Connection=True;"
            displayName: 'Deploy DACPAC'

          # - script: |
          #     sqlpackage /Action:Publish ^
          #       /SourceFile:"$(Pipeline.Workspace)\dacpac\FraudEngineDatabaseProject.dacpac" ^
          #       /TargetConnectionString:"Server=localhost;Database=FraudEngineDB;Trusted_Connection=True;"
          #   displayName: 'Deploy DACPAC'
