trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build SQL Project'
  inputs:
    command: 'build'
    projects: '**/*.sqlproj'
