trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: VSBuild@1
  displayName: 'Restore and Build Solution'
  inputs:
    solution: '**/*.sln'
    platform: 'Any CPU'
    configuration: 'Release'
    msbuildArgs: '/t:Restore,Build'
- task: CopyFiles@2
  inputs:
    Contents: '**\bin\Release\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish DACPAC Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dacpac'
    publishLocation: 'Container'